//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace FashionZone.DataLayer.Model
{
    public partial class D_ADDRESS_TYPE
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<ADDRESSINFO> ADDRESSINFO
        {
            get
            {
                if (_aDDRESSINFO == null)
                {
                    var newCollection = new FixupCollection<ADDRESSINFO>();
                    newCollection.CollectionChanged += FixupADDRESSINFO;
                    _aDDRESSINFO = newCollection;
                }
                return _aDDRESSINFO;
            }
            set
            {
                if (!ReferenceEquals(_aDDRESSINFO, value))
                {
                    var previousValue = _aDDRESSINFO as FixupCollection<ADDRESSINFO>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupADDRESSINFO;
                    }
                    _aDDRESSINFO = value;
                    var newValue = value as FixupCollection<ADDRESSINFO>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupADDRESSINFO;
                    }
                }
            }
        }
        private ICollection<ADDRESSINFO> _aDDRESSINFO;

        #endregion

        #region Association Fixup
    
        private void FixupADDRESSINFO(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ADDRESSINFO item in e.NewItems)
                {
                    item.D_ADDRESS_TYPE = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ADDRESSINFO item in e.OldItems)
                {
                    if (ReferenceEquals(item.D_ADDRESS_TYPE, this))
                    {
                        item.D_ADDRESS_TYPE = null;
                    }
                }
            }
        }

        #endregion

    }
}
