//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace FashionZone.DataLayer.Model
{
    public partial class EASYPAY_PAYMENT
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (PAYMENT != null && PAYMENT.ID != value)
                    {
                        PAYMENT = null;
                    }
                    _iD = value;
                }
            }
        }
        private int _iD;
    
        public virtual string TransactionID
        {
            get;
            set;
        }
    
        public virtual string MerchantUsername
        {
            get;
            set;
        }
    
        public virtual int ResponseCode
        {
            get;
            set;
        }
    
        public virtual string TransactionStatus
        {
            get;
            set;
        }
    
        public virtual string OriginalResponse
        {
            get;
            set;
        }
    
        public virtual decimal Amount
        {
            get;
            set;
        }
    
        public virtual decimal Rate
        {
            get;
            set;
        }
    
        public virtual System.DateTime Date
        {
            get;
            set;
        }
    
        public virtual decimal Fee
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual PAYMENT PAYMENT
        {
            get { return _pAYMENT; }
            set
            {
                if (!ReferenceEquals(_pAYMENT, value))
                {
                    var previousValue = _pAYMENT;
                    _pAYMENT = value;
                    FixupPAYMENT(previousValue);
                }
            }
        }
        private PAYMENT _pAYMENT;

        #endregion

        #region Association Fixup
    
        private void FixupPAYMENT(PAYMENT previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.EASYPAY_PAYMENT, this))
            {
                previousValue.EASYPAY_PAYMENT = null;
            }
    
            if (PAYMENT != null)
            {
                PAYMENT.EASYPAY_PAYMENT = this;
                if (ID != PAYMENT.ID)
                {
                    ID = PAYMENT.ID;
                }
            }
        }

        #endregion

    }
}
