//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace FashionZone.DataLayer.Model
{
    public partial class INVITATION
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CustomerID
        {
            get { return _customerID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_customerID != value)
                    {
                        if (CUSTOMER != null && CUSTOMER.ID != value)
                        {
                            CUSTOMER = null;
                        }
                        _customerID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _customerID;
    
        public virtual string InvitedMail
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Registered
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> RegistrationDate
        {
            get;
            set;
        }
    
        public virtual string IP
        {
            get;
            set;
        }
    
        public virtual string Cookie
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual CUSTOMER CUSTOMER
        {
            get { return _cUSTOMER; }
            set
            {
                if (!ReferenceEquals(_cUSTOMER, value))
                {
                    var previousValue = _cUSTOMER;
                    _cUSTOMER = value;
                    FixupCUSTOMER(previousValue);
                }
            }
        }
        private CUSTOMER _cUSTOMER;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCUSTOMER(CUSTOMER previousValue)
        {
            if (previousValue != null && previousValue.INVITATION.Contains(this))
            {
                previousValue.INVITATION.Remove(this);
            }
    
            if (CUSTOMER != null)
            {
                if (!CUSTOMER.INVITATION.Contains(this))
                {
                    CUSTOMER.INVITATION.Add(this);
                }
                if (CustomerID != CUSTOMER.ID)
                {
                    CustomerID = CUSTOMER.ID;
                }
            }
            else if (!_settingFK)
            {
                CustomerID = null;
            }
        }

        #endregion

    }
}
