//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace FashionZone.DataLayer.Model
{
    public partial class LOG
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Type
        {
            get;
            set;
        }
    
        public virtual string Message
        {
            get;
            set;
        }
    
        public virtual string StackTrace
        {
            get;
            set;
        }
    
        public virtual string Class
        {
            get;
            set;
        }
    
        public virtual string Method
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LineNumber
        {
            get;
            set;
        }

        #endregion

    }
}
