//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace FashionZone.DataLayer.Model
{
    public partial class PRODUCT_ATTRIBUTE
    {
        #region Primitive Properties
    
        public virtual int ProductID
        {
            get { return _productID; }
            set
            {
                if (_productID != value)
                {
                    if (PRODUCT != null && PRODUCT.ID != value)
                    {
                        PRODUCT = null;
                    }
                    _productID = value;
                }
            }
        }
        private int _productID;
    
        public virtual int AttributeValueID
        {
            get { return _attributeValueID; }
            set
            {
                if (_attributeValueID != value)
                {
                    if (D_ATTRIBUTE_VALUE != null && D_ATTRIBUTE_VALUE.ID != value)
                    {
                        D_ATTRIBUTE_VALUE = null;
                    }
                    _attributeValueID = value;
                }
            }
        }
        private int _attributeValueID;
    
        public virtual int Quantity
        {
            get;
            set;
        }
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int Availability
        {
            get;
            set;
        }
    
        public virtual byte[] Version
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual PRODUCT PRODUCT
        {
            get { return _pRODUCT; }
            set
            {
                if (!ReferenceEquals(_pRODUCT, value))
                {
                    var previousValue = _pRODUCT;
                    _pRODUCT = value;
                    FixupPRODUCT(previousValue);
                }
            }
        }
        private PRODUCT _pRODUCT;
    
        public virtual D_ATTRIBUTE_VALUE D_ATTRIBUTE_VALUE
        {
            get { return _d_ATTRIBUTE_VALUE; }
            set
            {
                if (!ReferenceEquals(_d_ATTRIBUTE_VALUE, value))
                {
                    var previousValue = _d_ATTRIBUTE_VALUE;
                    _d_ATTRIBUTE_VALUE = value;
                    FixupD_ATTRIBUTE_VALUE(previousValue);
                }
            }
        }
        private D_ATTRIBUTE_VALUE _d_ATTRIBUTE_VALUE;
    
        public virtual ICollection<ORDER_DETAIL> ORDER_DETAIL
        {
            get
            {
                if (_oRDER_DETAIL == null)
                {
                    var newCollection = new FixupCollection<ORDER_DETAIL>();
                    newCollection.CollectionChanged += FixupORDER_DETAIL;
                    _oRDER_DETAIL = newCollection;
                }
                return _oRDER_DETAIL;
            }
            set
            {
                if (!ReferenceEquals(_oRDER_DETAIL, value))
                {
                    var previousValue = _oRDER_DETAIL as FixupCollection<ORDER_DETAIL>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupORDER_DETAIL;
                    }
                    _oRDER_DETAIL = value;
                    var newValue = value as FixupCollection<ORDER_DETAIL>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupORDER_DETAIL;
                    }
                }
            }
        }
        private ICollection<ORDER_DETAIL> _oRDER_DETAIL;
    
        public virtual ICollection<SHOPPING_CART> SHOPPING_CART
        {
            get
            {
                if (_sHOPPING_CART == null)
                {
                    var newCollection = new FixupCollection<SHOPPING_CART>();
                    newCollection.CollectionChanged += FixupSHOPPING_CART;
                    _sHOPPING_CART = newCollection;
                }
                return _sHOPPING_CART;
            }
            set
            {
                if (!ReferenceEquals(_sHOPPING_CART, value))
                {
                    var previousValue = _sHOPPING_CART as FixupCollection<SHOPPING_CART>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSHOPPING_CART;
                    }
                    _sHOPPING_CART = value;
                    var newValue = value as FixupCollection<SHOPPING_CART>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSHOPPING_CART;
                    }
                }
            }
        }
        private ICollection<SHOPPING_CART> _sHOPPING_CART;

        #endregion

        #region Association Fixup
    
        private void FixupPRODUCT(PRODUCT previousValue)
        {
            if (previousValue != null && previousValue.PRODUCT_ATTRIBUTE.Contains(this))
            {
                previousValue.PRODUCT_ATTRIBUTE.Remove(this);
            }
    
            if (PRODUCT != null)
            {
                if (!PRODUCT.PRODUCT_ATTRIBUTE.Contains(this))
                {
                    PRODUCT.PRODUCT_ATTRIBUTE.Add(this);
                }
                if (ProductID != PRODUCT.ID)
                {
                    ProductID = PRODUCT.ID;
                }
            }
        }
    
        private void FixupD_ATTRIBUTE_VALUE(D_ATTRIBUTE_VALUE previousValue)
        {
            if (previousValue != null && previousValue.PRODUCT_ATTRIBUTE.Contains(this))
            {
                previousValue.PRODUCT_ATTRIBUTE.Remove(this);
            }
    
            if (D_ATTRIBUTE_VALUE != null)
            {
                if (!D_ATTRIBUTE_VALUE.PRODUCT_ATTRIBUTE.Contains(this))
                {
                    D_ATTRIBUTE_VALUE.PRODUCT_ATTRIBUTE.Add(this);
                }
                if (AttributeValueID != D_ATTRIBUTE_VALUE.ID)
                {
                    AttributeValueID = D_ATTRIBUTE_VALUE.ID;
                }
            }
        }
    
        private void FixupORDER_DETAIL(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ORDER_DETAIL item in e.NewItems)
                {
                    item.PRODUCT_ATTRIBUTE = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ORDER_DETAIL item in e.OldItems)
                {
                    if (ReferenceEquals(item.PRODUCT_ATTRIBUTE, this))
                    {
                        item.PRODUCT_ATTRIBUTE = null;
                    }
                }
            }
        }
    
        private void FixupSHOPPING_CART(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SHOPPING_CART item in e.NewItems)
                {
                    item.PRODUCT_ATTRIBUTE = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SHOPPING_CART item in e.OldItems)
                {
                    if (ReferenceEquals(item.PRODUCT_ATTRIBUTE, this))
                    {
                        item.PRODUCT_ATTRIBUTE = null;
                    }
                }
            }
        }

        #endregion

    }
}
