//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace FashionZone.DataLayer.Model
{
    public partial class ROLE
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<USER> USER
        {
            get
            {
                if (_uSER == null)
                {
                    var newCollection = new FixupCollection<USER>();
                    newCollection.CollectionChanged += FixupUSER;
                    _uSER = newCollection;
                }
                return _uSER;
            }
            set
            {
                if (!ReferenceEquals(_uSER, value))
                {
                    var previousValue = _uSER as FixupCollection<USER>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUSER;
                    }
                    _uSER = value;
                    var newValue = value as FixupCollection<USER>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUSER;
                    }
                }
            }
        }
        private ICollection<USER> _uSER;

        #endregion

        #region Association Fixup
    
        private void FixupUSER(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (USER item in e.NewItems)
                {
                    item.ROLE = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (USER item in e.OldItems)
                {
                    if (ReferenceEquals(item.ROLE, this))
                    {
                        item.ROLE = null;
                    }
                }
            }
        }

        #endregion

    }
}
