CREATE TABLE [dbo].[CASH_PAYMENT] (
    [ID]       INT             NOT NULL,
    [Receiver] VARCHAR (50)    NULL,
    [Amount]   DECIMAL (18, 2) NULL,
    [PaidOn]   SMALLDATETIME   NULL,
    [Comments] VARCHAR (250)   NULL,
    CONSTRAINT [PK_CASH_PAYMENT_1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CASH_PAYMENT_PAYMENT] FOREIGN KEY ([ID]) REFERENCES [dbo].[PAYMENT] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

