CREATE TABLE [dbo].[D_RETURN_MOTIVATION] (
    [ID]   INT          IDENTITY (1, 1) NOT NULL,
    [Name] VARCHAR (70) NULL,
    CONSTRAINT [PK_D_RETURN_MOTIVATION] PRIMARY KEY CLUSTERED ([ID] ASC)
);

