CREATE TABLE [dbo].[ORDER_BONUS] (
    [OrderID] INT            NOT NULL,
    [BonusID] INT            NOT NULL,
    [Value]   DECIMAL (6, 2) NULL,
    CONSTRAINT [PK_ORDER_BONUS] PRIMARY KEY CLUSTERED ([OrderID] ASC, [BonusID] ASC),
    CONSTRAINT [FK_ORDER_BONUS_BONUS] FOREIGN KEY ([BonusID]) REFERENCES [dbo].[BONUS] ([ID]),
    CONSTRAINT [FK_ORDER_BONUS_ORDERS] FOREIGN KEY ([OrderID]) REFERENCES [dbo].[ORDERS] ([ID])
);

