CREATE TABLE [dbo].[ORDER_DETAIL] (
    [OrderID]    INT NOT NULL,
    [Quantity]   INT NOT NULL,
    [ProdAttrID] INT NOT NULL,
    [CampaignID] INT NOT NULL,
    [ID]         INT IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_ORDER_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ORDER_DETAIL_CAMPAIGN] FOREIGN KEY ([CampaignID]) REFERENCES [dbo].[CAMPAIGN] ([ID]),
    CONSTRAINT [FK_PURCHASE_DETAIL_PRODUCT_ATTRIBUTE] FOREIGN KEY ([ProdAttrID]) REFERENCES [dbo].[PRODUCT_ATTRIBUTE] ([ID]),
    CONSTRAINT [FK_PURCHASE_DETAIL_PURCHASE] FOREIGN KEY ([OrderID]) REFERENCES [dbo].[ORDERS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_ORDER_DETAIL]
    ON [dbo].[ORDER_DETAIL]([OrderID] ASC, [ProdAttrID] ASC);

