CREATE TABLE [dbo].[PAYMENT] (
    [ID]   INT NOT NULL,
    [Type] INT NOT NULL,
    CONSTRAINT [PK_PAYMENT] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PAYMENT_ORDERS] FOREIGN KEY ([ID]) REFERENCES [dbo].[ORDERS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

