CREATE TABLE [dbo].[PRODUCT_CATEGORY] (
    [ProductID]  INT NOT NULL,
    [CategoryID] INT NOT NULL,
    CONSTRAINT [PK_PRODUCT_CATEGORY_1] PRIMARY KEY CLUSTERED ([ProductID] ASC, [CategoryID] ASC),
    CONSTRAINT [FK_PRODUCT_CATEGORY_CATEGORY] FOREIGN KEY ([CategoryID]) REFERENCES [dbo].[CATEGORY] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_PRODUCT_CATEGORY_PRODUCT] FOREIGN KEY ([ProductID]) REFERENCES [dbo].[PRODUCT] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

