CREATE TABLE [dbo].[PRODUCT_ATTRIBUTE] (
    [ProductID]        INT        NOT NULL,
    [AttributeValueID] INT        NOT NULL,
    [Quantity]         INT        NOT NULL,
    [ID]               INT        IDENTITY (1, 1) NOT NULL,
    [Availability]     INT        NOT NULL,
    [Version]          ROWVERSION NULL,
    CONSTRAINT [PK_PRODUCT_ATTRIBUTE_1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PRODUCT_ATTRIBUTE_D_ATTRIBUTE_VALUE] FOREIGN KEY ([AttributeValueID]) REFERENCES [dbo].[D_ATTRIBUTE_VALUE] ([ID]),
    CONSTRAINT [FK_PRODUCT_ATTRIBUTE_PRODUCT] FOREIGN KEY ([ProductID]) REFERENCES [dbo].[PRODUCT] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [IX_PRODUCT_ATTRIBUTE] UNIQUE NONCLUSTERED ([ProductID] ASC, [AttributeValueID] ASC)
);

