CREATE TABLE [dbo].[SHOPPING_CART] (
    [ID]         CHAR (20)     NOT NULL,
    [Quantity]   INT           CONSTRAINT [DF_SHOPPING_CART_Quantity] DEFAULT ((0)) NOT NULL,
    [DateAdded]  SMALLDATETIME NOT NULL,
    [ProdAttrID] INT           NOT NULL,
    [CustomerID] INT           NOT NULL,
    [CampaignID] INT           NOT NULL,
    [FrontEnd]   BIT           NULL,
    CONSTRAINT [PK_SHOPPING_CART] PRIMARY KEY CLUSTERED ([ID] ASC, [ProdAttrID] ASC),
    CONSTRAINT [FK_SHOPPING_CART_CAMPAIGN] FOREIGN KEY ([CampaignID]) REFERENCES [dbo].[CAMPAIGN] ([ID]),
    CONSTRAINT [FK_SHOPPING_CART_CUSTOMER] FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[CUSTOMER] ([ID]),
    CONSTRAINT [FK_SHOPPING_CART_PRODUCT_ATTRIBUTE] FOREIGN KEY ([ProdAttrID]) REFERENCES [dbo].[PRODUCT_ATTRIBUTE] ([ID])
);

