CREATE LOGIN [privalb] WITH PASSWORD=N'ú¹·d´çµSwÃ)«¤zd6Òê£(WB', DEFAULT_DATABASE=[priv], DEFAULT_LANGUAGE=[Italiano], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE USER [privalb] WITH DEFAULT_SCHEMA=[dbo]