//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rreth nesh.
        /// </summary>
        internal static string AboutUsLabel {
            get {
                return ResourceManager.GetString("AboutUsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsulto produktet e markës.
        /// </summary>
        internal static string AccessSaleLabel {
            get {
                return ResourceManager.GetString("AccessSaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikohu ne sit.
        /// </summary>
        internal static string AccessTheSiteLabel {
            get {
                return ResourceManager.GetString("AccessTheSiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markat aktive në FZone në këtë moment.
        /// </summary>
        internal static string ActualCampaignsIntroLabel {
            get {
                return ResourceManager.GetString("ActualCampaignsIntroLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fushata në këtë moment.
        /// </summary>
        internal static string ActualCampaignsLabel {
            get {
                return ResourceManager.GetString("ActualCampaignsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto adresë.
        /// </summary>
        internal static string AddAddressLabel {
            get {
                return ResourceManager.GetString("AddAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        internal static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri i adresës.
        /// </summary>
        internal static string AddressNameLabel {
            get {
                return ResourceManager.GetString("AddressNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto në shportë.
        /// </summary>
        internal static string AddToBasketLink {
            get {
                return ResourceManager.GetString("AddToBasketLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të gjitha.
        /// </summary>
        internal static string AllMenuLabel {
            get {
                return ResourceManager.GetString("AllMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email i regjistruar me pare..
        /// </summary>
        internal static string AlreadyRegisteredMailLabel {
            get {
                return ResourceManager.GetString("AlreadyRegisteredMailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totali.
        /// </summary>
        internal static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je i regjistruar?.
        /// </summary>
        internal static string AreYourRegisteredLabel {
            get {
                return ResourceManager.GetString("AreYourRegisteredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string AssignedDateLabel {
            get {
                return ResourceManager.GetString("AssignedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pranë zyrave tona.
        /// </summary>
        internal static string AtOurOfficeLabel {
            get {
                return ResourceManager.GetString("AtOurOfficeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I disponueshem.
        /// </summary>
        internal static string AvailableBonusLabel {
            get {
                return ResourceManager.GetString("AvailableBonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I disponueshëm.
        /// </summary>
        internal static string AvailableLabel {
            get {
                return ResourceManager.GetString("AvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datëlindja.
        /// </summary>
        internal static string BirthdayLabel {
            get {
                return ResourceManager.GetString("BirthdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string BonusLabel {
            get {
                return ResourceManager.GetString("BonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probleme gjatë blerjes.
        /// </summary>
        internal static string BuyProblemLabel {
            get {
                return ResourceManager.GetString("BuyProblemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fushata.
        /// </summary>
        internal static string CampaignLabel {
            get {
                return ResourceManager.GetString("CampaignLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Së shpejti.
        /// </summary>
        internal static string CampaignSoonLabel {
            get {
                return ResourceManager.GetString("CampaignSoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulo shportën.
        /// </summary>
        internal static string CancelCartLabel {
            get {
                return ResourceManager.GetString("CancelCartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeni të sigurtë për anullimin e shportës suaj?.
        /// </summary>
        internal static string CancelCartQuestion {
            get {
                return ResourceManager.GetString("CancelCartQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulo.
        /// </summary>
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeni të sigurtë për anullimin e kësaj porosie?.
        /// </summary>
        internal static string CancelOrderQuestion {
            get {
                return ResourceManager.GetString("CancelOrderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shporta juaj skadoi. Produktet që përmbante u kthyen të disponueshme në vitrinë. Nxitoni për ti porositur sërish..
        /// </summary>
        internal static string CartExpired {
            get {
                return ResourceManager.GetString("CartExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shporta juaj skadon per.
        /// </summary>
        internal static string CartExpiresInLabel {
            get {
                return ResourceManager.GetString("CartExpiresInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per te perfunduar porosine klikoni mbi porosit tani para skadimit te shportes..
        /// </summary>
        internal static string CartExpiringInfo {
            get {
                return ResourceManager.GetString("CartExpiringInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porosit tani.
        /// </summary>
        internal static string CheckoutLabel {
            get {
                return ResourceManager.GetString("CheckoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fëmijë.
        /// </summary>
        internal static string ChildMenuLabel {
            get {
                return ResourceManager.GetString("ChildMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgjidh bonus.
        /// </summary>
        internal static string ChooseLabel {
            get {
                return ResourceManager.GetString("ChooseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qyteti.
        /// </summary>
        internal static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompania.
        /// </summary>
        internal static string CompanyLabel {
            get {
                return ResourceManager.GetString("CompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pranoj Kushtet e Përgjithshme të Shitjes të fzone.al..
        /// </summary>
        internal static string ConditionAcceptanceText {
            get {
                return ResourceManager.GetString("ConditionAcceptanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmo.
        /// </summary>
        internal static string ConfirmLabel {
            get {
                return ResourceManager.GetString("ConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to përdorues në sit.
        /// </summary>
        internal static string ConnectedUsersLabel {
            get {
                return ResourceManager.GetString("ConnectedUsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        internal static string ContactLabel {
            get {
                return ResourceManager.GetString("ContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërkesa e juaj u dergua. Shërbimi ndaj klientit do t&apos;ju përgjigjet sa më parë kërkeses suaj.
        /// </summary>
        internal static string ContactRequestSent {
            get {
                return ResourceManager.GetString("ContactRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vazhdo shopping.
        /// </summary>
        internal static string ContinueShoppingLabel {
            get {
                return ResourceManager.GetString("ContinueShoppingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat u ruajtën me sukses..
        /// </summary>
        internal static string DataSavedCorrectly {
            get {
                return ResourceManager.GetString("DataSavedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeni i sigurtë per fshirjen e kesaj adrese?.
        /// </summary>
        internal static string DeleteAddressQuestion {
            get {
                return ResourceManager.GetString("DeleteAddressQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimino.
        /// </summary>
        internal static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa e dërgimit.
        /// </summary>
        internal static string DeliveryAddressLabel {
            get {
                return ResourceManager.GetString("DeliveryAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dërgimi.
        /// </summary>
        internal static string DeliveryLabel {
            get {
                return ResourceManager.GetString("DeliveryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përshkrimi.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaje.
        /// </summary>
        internal static string DetailLabel {
            get {
                return ResourceManager.GetString("DetailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko.
        /// </summary>
        internal static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email i ftuar më parë.
        /// </summary>
        internal static string EmailAlreadyInvited {
            get {
                return ResourceManager.GetString("EmailAlreadyInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ky e-mail nuk egziston në bazën tonë të të dhënave..
        /// </summary>
        internal static string EmailNotExisting {
            get {
                return ResourceManager.GetString("EmailNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shporta juaj nuk përmban asnjë produkt..
        /// </summary>
        internal static string EmptyCartLabel {
            get {
                return ResourceManager.GetString("EmptyCartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendosni fjalëkalimin tuaj te ri..
        /// </summary>
        internal static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyr ne club-in e fzone.al.
        /// </summary>
        internal static string EnterTheClubLabel {
            get {
                return ResourceManager.GetString("EnterTheClubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U verifikua nje problem ne pagesen tuaj. Stafi yne do te kryeje verifikimet e duhura dhe do t&apos;ju kontaktoje per t&apos;ju informuar..
        /// </summary>
        internal static string ErrorInPayPalLabel {
            get {
                return ResourceManager.GetString("ErrorInPayPalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U verifikua një problem teknik..
        /// </summary>
        internal static string ErrorVerifiedLabel {
            get {
                return ResourceManager.GetString("ErrorVerifiedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dërgimi i parashikuar për:.
        /// </summary>
        internal static string EstimatedDeliveryLabel {
            get {
                return ResourceManager.GetString("EstimatedDeliveryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përfitoni ulje ekskluzive.
        /// </summary>
        internal static string ExclusiveSalesLabel {
            get {
                return ResourceManager.GetString("ExclusiveSalesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skadon.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na ndiq.
        /// </summary>
        internal static string FollowUsLabel {
            get {
                return ResourceManager.GetString("FollowUsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kam harruar fjalëkalimin.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miqtë e tu.
        /// </summary>
        internal static string FriendsLabel {
            get {
                return ResourceManager.GetString("FriendsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nga.
        /// </summary>
        internal static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FZONE.AL.
        /// </summary>
        internal static string FZONEALLabel {
            get {
                return ResourceManager.GetString("FZONEALLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjinia.
        /// </summary>
        internal static string GenderLabel {
            get {
                return ResourceManager.GetString("GenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shko tek detajet.
        /// </summary>
        internal static string GoToProductDetailLabel {
            get {
                return ResourceManager.GetString("GoToProductDetailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDIHME.
        /// </summary>
        internal static string HelpAndContactLabel {
            get {
                return ResourceManager.GetString("HelpAndContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreu.
        /// </summary>
        internal static string HomeMenuLabel {
            get {
                return ResourceManager.GetString("HomeMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion.
        /// </summary>
        internal static string InformationLabel {
            get {
                return ResourceManager.GetString("InformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacione.
        /// </summary>
        internal static string InformationsHeadLabel {
            get {
                return ResourceManager.GetString("InformationsHeadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
        ///exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
        ///pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..
        /// </summary>
        internal static string InformationsTextLabel {
            get {
                return ResourceManager.GetString("InformationsTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibiliteti për këtë produkt është i pamjaftueshëm për sasinë e kërkuar. Zgjidhni një sasi më të vogël..
        /// </summary>
        internal static string InsufficientAvailabilityMessage {
            get {
                return ResourceManager.GetString("InsufficientAvailabilityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fto miqtë e tu dhe fito 5 .
        /// </summary>
        internal static string InviteAndWinLabel {
            get {
                return ResourceManager.GetString("InviteAndWinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoku yt.
        /// </summary>
        internal static string InviteBody1MailLabel {
            get {
                return ResourceManager.GetString("InviteBody1MailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to të dërgoi nje ftesë për të parë markat më eksluzive në.
        /// </summary>
        internal static string InviteBody2MailLabel {
            get {
                return ResourceManager.GetString("InviteBody2MailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTO.
        /// </summary>
        internal static string InviteLabel {
            get {
                return ResourceManager.GetString("InviteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ju fton te regjistroheni për të përfituar nga shitjet eksluzive!.
        /// </summary>
        internal static string InviteSubjectMailLabel {
            get {
                return ResourceManager.GetString("InviteSubjectMailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ftesa u dërgua me sukses. Në momentin e blerjes së parë të të fuarit tuaj, ju do të përfitoni 5 € bonus për blerje në sitin tonë..
        /// </summary>
        internal static string InviteSuccessful {
            get {
                return ResourceManager.GetString("InviteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura.
        /// </summary>
        internal static string InvoiceLabel {
            get {
                return ResourceManager.GetString("InvoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikulli.
        /// </summary>
        internal static string ItemLabel {
            get {
                return ResourceManager.GetString("ItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokaliteti.
        /// </summary>
        internal static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikimi dështoi. Ju lutemi të provoni përsëri..
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikohu.
        /// </summary>
        internal static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string LogoutLabel {
            get {
                return ResourceManager.GetString("LogoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail nuk perkon.
        /// </summary>
        internal static string MailMismatchLabel {
            get {
                return ResourceManager.GetString("MailMismatchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mund të vendosni më shumë se një email, duke i ndarë me presje (pa hapësirë)..
        /// </summary>
        internal static string MailSeparatorLabel {
            get {
                return ResourceManager.GetString("MailSeparatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meshkuj.
        /// </summary>
        internal static string ManMenuLabel {
            get {
                return ResourceManager.GetString("ManMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr maksimal i adresave ështe 5..
        /// </summary>
        internal static string MaximumAddressLabel {
            get {
                return ResourceManager.GetString("MaximumAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minuta..
        /// </summary>
        internal static string MinutesLabel {
            get {
                return ResourceManager.GetString("MinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disa fusha mungojne..
        /// </summary>
        internal static string MissingFields {
            get {
                return ResourceManager.GetString("MissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        internal static string MobileLabel {
            get {
                return ResourceManager.GetString("MobileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ME SHUME.
        /// </summary>
        internal static string MoreLabel {
            get {
                return ResourceManager.GetString("MoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivi.
        /// </summary>
        internal static string MotivationLabel {
            get {
                return ResourceManager.GetString("MotivationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILI IM.
        /// </summary>
        internal static string MyAccountLabel {
            get {
                return ResourceManager.GetString("MyAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili im.
        /// </summary>
        internal static string MyAccountLowerLabel {
            get {
                return ResourceManager.GetString("MyAccountLowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresat.
        /// </summary>
        internal static string MyAddresesHeadLabel {
            get {
                return ResourceManager.GetString("MyAddresesHeadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresat e mia.
        /// </summary>
        internal static string MyAddressesLabel {
            get {
                return ResourceManager.GetString("MyAddressesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shporta ime.
        /// </summary>
        internal static string MyCartLabel {
            get {
                return ResourceManager.GetString("MyCartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat e mia.
        /// </summary>
        internal static string MyInfoLabel {
            get {
                return ResourceManager.GetString("MyInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të ftuarit e mi.
        /// </summary>
        internal static string MyInviteesLabel {
            get {
                return ResourceManager.GetString("MyInviteesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POROSITE E MIA.
        /// </summary>
        internal static string MyOrdersLabel {
            get {
                return ResourceManager.GetString("MyOrdersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porositë e mia.
        /// </summary>
        internal static string MyOrdersLowerLabel {
            get {
                return ResourceManager.GetString("MyOrdersLowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Këtu mund të shikoni Porositë tuaja, dhë të kontrolloni të gjitha detajet duke klikuar në info.
        ///Te seksioni gjendja mund të kontrolloni herë pas here ecurinë e dergesës së produktit që keni blerë..
        /// </summary>
        internal static string MyOrdersTextLabel {
            get {
                return ResourceManager.GetString("MyOrdersTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonot e mia.
        /// </summary>
        internal static string MyVoucherLabel {
            get {
                return ResourceManager.GetString("MyVoucherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i ri.
        /// </summary>
        internal static string NewPassLabel {
            get {
                return ResourceManager.GetString("NewPassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dëshiroj të informohem nëpërmjet email-it rreth ofertave të markave në fzone.al.
        /// </summary>
        internal static string NewsletterAcceptanceText {
            get {
                return ResourceManager.GetString("NewsletterAcceptanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jo.
        /// </summary>
        internal static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komente.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Njoftime.
        /// </summary>
        internal static string NotificationHeadLabel {
            get {
                return ResourceManager.GetString("NotificationHeadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Për të aktivizuar shërbimin e njoftimeve me mail cdo ditë..
        /// </summary>
        internal static string NotifTextDailyLabel {
            get {
                return ResourceManager.GetString("NotifTextDailyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Për të aktivizuar shërbimin e njoftimeve  me mail për ofertat SPECIALE.
        /// </summary>
        internal static string NotifTextSpecialLabel {
            get {
                return ResourceManager.GetString("NotifTextSpecialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Për të aktivizuar shërbimin e njoftimeve me mail cdo javë..
        /// </summary>
        internal static string NotifTextWeeklyLabel {
            get {
                return ResourceManager.GetString("NotifTextWeeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i pavlefshëm.
        /// </summary>
        internal static string NotValidLabel {
            get {
                return ResourceManager.GetString("NotValidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i vjetër.
        /// </summary>
        internal static string OldPassLabel {
            get {
                return ResourceManager.GetString("OldPassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ne blerjen e tyre te pare).
        /// </summary>
        internal static string OnFirstBuy {
            get {
                return ResourceManager.GetString("OnFirstBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vetëm.
        /// </summary>
        internal static string OnlyLabel {
            get {
                return ResourceManager.GetString("OnlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e porosisë.
        /// </summary>
        internal static string OrderDateLabel {
            get {
                return ResourceManager.GetString("OrderDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porosi.
        /// </summary>
        internal static string OrderLabel {
            get {
                return ResourceManager.GetString("OrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjetër.
        /// </summary>
        internal static string OtherLabel {
            get {
                return ResourceManager.GetString("OtherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagesa juaj po kalon tek EasyPay. Ju Lutem prisni....
        /// </summary>
        internal static string PassingToEasypayLabel {
            get {
                return ResourceManager.GetString("PassingToEasypayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagesa juaj po kalon tek PayPal. Ju Lutem prisni....
        /// </summary>
        internal static string PassingToPaypalLabel {
            get {
                return ResourceManager.GetString("PassingToPaypalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klikoni në link-un e mëposhtëm dhe zgjidhni passwordin tuaj të ri..
        /// </summary>
        internal static string PasswordLinkClick {
            get {
                return ResourceManager.GetString("PasswordLinkClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruksionet u derguan në email-in tuaj..
        /// </summary>
        internal static string PasswordLinkSent {
            get {
                return ResourceManager.GetString("PasswordLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Një link me instruksione do të dërgohet në e-mailin tuaj, për të zgjedhur një password të ri..
        /// </summary>
        internal static string PasswordMail {
            get {
                return ResourceManager.GetString("PasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i ri - FZone.
        /// </summary>
        internal static string PasswordMailSubject {
            get {
                return ResourceManager.GetString("PasswordMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimet nuk perkojne..
        /// </summary>
        internal static string PasswordMismatchLabel {
            get {
                return ResourceManager.GetString("PasswordMismatchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info e pagimit.
        /// </summary>
        internal static string PaymentDataLabel {
            get {
                return ResourceManager.GetString("PaymentDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagesa.
        /// </summary>
        internal static string PaymentLabel {
            get {
                return ResourceManager.GetString("PaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mënyrat e pagesës.
        /// </summary>
        internal static string PaymentMethodsLabel {
            get {
                return ResourceManager.GetString("PaymentMethodsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagesa juaj nuk u krye..
        /// </summary>
        internal static string PaymentProblemLiteral {
            get {
                return ResourceManager.GetString("PaymentProblemLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faleminderit per pagesen tuaj..
        /// </summary>
        internal static string PayPalThankyouLabel {
            get {
                return ResourceManager.GetString("PayPalThankyouLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probleme me pagimin.
        /// </summary>
        internal static string PayProblemLabel {
            get {
                return ResourceManager.GetString("PayProblemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të Dhënat.
        /// </summary>
        internal static string PersonalDataHeadLabel {
            get {
                return ResourceManager.GetString("PersonalDataHeadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat personale.
        /// </summary>
        internal static string PersonalDataLabel {
            get {
                return ResourceManager.GetString("PersonalDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju lutemi të pranoni kushtet e përdorimit përpara se të regjistroheni..
        /// </summary>
        internal static string PleaseAcceptLabel {
            get {
                return ResourceManager.GetString("PleaseAcceptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shërbimet pas shitjes.
        /// </summary>
        internal static string PostSellServicesLabel {
            get {
                return ResourceManager.GetString("PostSellServicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmimi.
        /// </summary>
        internal static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string PrivacyStatementLabel {
            get {
                return ResourceManager.GetString("PrivacyStatementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kujdes! Ky cmim është ekskluziv për FZone. Në rast se paraqiteni pa faturen e FZone, dyqani aplikon cmimin e plotë..
        /// </summary>
        internal static string ProductExclusivityLabel {
            get {
                return ResourceManager.GetString("ProductExclusivityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkti.
        /// </summary>
        internal static string ProductLabel {
            get {
                return ResourceManager.GetString("ProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatkeqësisht, ky produkt nuk është më i disponueshëm..
        /// </summary>
        internal static string ProductNotAvailableLiteral {
            get {
                return ResourceManager.GetString("ProductNotAvailableLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ky produkt mund të terhiqet pranë dyqanit të mëposhtëm me faturën e FZone.
        /// </summary>
        internal static string ProductPickUpLabel {
            get {
                return ResourceManager.GetString("ProductPickUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sasia.
        /// </summary>
        internal static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Regjistruar.
        /// </summary>
        internal static string RegisteredLabel {
            get {
                return ResourceManager.GetString("RegisteredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regjistrohu.
        /// </summary>
        internal static string RegisterLabel {
            get {
                return ResourceManager.GetString("RegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e Regjistrimit.
        /// </summary>
        internal static string RegistrationDateLabel {
            get {
                return ResourceManager.GetString("RegistrationDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probleme gjatë regjistrimit.
        /// </summary>
        internal static string RegProblemLabel {
            get {
                return ResourceManager.GetString("RegProblemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiqe.
        /// </summary>
        internal static string RemoveLabel {
            get {
                return ResourceManager.GetString("RemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doni të hiqni produktin .
        /// </summary>
        internal static string RemoveProductQuestion {
            get {
                return ResourceManager.GetString("RemoveProductQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përserite.
        /// </summary>
        internal static string RepeatLabel {
            get {
                return ResourceManager.GetString("RepeatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përsërit fjalëkalimin.
        /// </summary>
        internal static string RepeatPasswordLabel {
            get {
                return ResourceManager.GetString("RepeatPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërkesa.
        /// </summary>
        internal static string RequestLabel {
            get {
                return ResourceManager.GetString("RequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kthimet dhe rimbursimet.
        /// </summary>
        internal static string ReturnsAndRefundsLabel {
            get {
                return ResourceManager.GetString("ReturnsAndRefundsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo e shitjeve.
        /// </summary>
        internal static string SalesReminderLabel {
            get {
                return ResourceManager.GetString("SalesReminderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruaj.
        /// </summary>
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail u ruajt me sukses.
        /// </summary>
        internal static string SaveMailLabel {
            get {
                return ResourceManager.GetString("SaveMailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwordi u ruajt me sukses.
        /// </summary>
        internal static string SavePwMsgLabel {
            get {
                return ResourceManager.GetString("SavePwMsgLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruani kodin e transaksionit te veprimit:.
        /// </summary>
        internal static string SaveTransactionID {
            get {
                return ResourceManager.GetString("SaveTransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguria mbi transaksionet e pagimit.
        /// </summary>
        internal static string SecureTransactionsLabel {
            get {
                return ResourceManager.GetString("SecureTransactionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faqja fzone.al është e pajisur me një sistem mbrojtje nga më efektivët që ekzistojnë aktualisht. Faqja e internetit nuk ka miratuar vetëm procedurën e kodimit SSL (Secure Socket Layer), por në të njëjtën kohë ka përforcuar procedurat për anti-interferencat dhe kodifikimin për të ruajtur sa më tepër të jetë e mundur të dhënat e lidhura me mjetet e pagesës. Fzone.al nuk ka akses në të dhënat konfidenciale në lidhje me mjetet e pagesës. Në fakt, vetëm Paypal / Easypay ka informacion (për numrin e kartës së kre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecureTransactionsTextLabel {
            get {
                return ResourceManager.GetString("SecureTransactionsTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguria.
        /// </summary>
        internal static string SecurityLabel {
            get {
                return ResourceManager.GetString("SecurityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgjidh masën.
        /// </summary>
        internal static string SelectSizeLabel {
            get {
                return ResourceManager.GetString("SelectSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kushtet e shitjes.
        /// </summary>
        internal static string SellingTerms {
            get {
                return ResourceManager.GetString("SellingTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dërgo.
        /// </summary>
        internal static string SendLabel {
            get {
                return ResourceManager.GetString("SendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosto e dërgimit.
        /// </summary>
        internal static string ShippingCostLabel {
            get {
                return ResourceManager.GetString("ShippingCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbërritja e pakos.
        /// </summary>
        internal static string ShippingEndLabel {
            get {
                return ResourceManager.GetString("ShippingEndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e dërgimit.
        /// </summary>
        internal static string ShippingStartLabel {
            get {
                return ResourceManager.GetString("ShippingStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masa.
        /// </summary>
        internal static string SizeLabel {
            get {
                return ResourceManager.GetString("SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju lutemi vendosni një adresë te vlefshme për dërgimin.
        /// </summary>
        internal static string SpecifyShippingAddress {
            get {
                return ResourceManager.GetString("SpecifyShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjëndja.
        /// </summary>
        internal static string StateLabel {
            get {
                return ResourceManager.GetString("StateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rruga.
        /// </summary>
        internal static string StreetLabel {
            get {
                return ResourceManager.GetString("StreetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nëntotali.
        /// </summary>
        internal static string SubTotalLabel {
            get {
                return ResourceManager.GetString("SubTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbiemri.
        /// </summary>
        internal static string SurnameLabel {
            get {
                return ResourceManager.GetString("SurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoni.
        /// </summary>
        internal static string TelLabel {
            get {
                return ResourceManager.GetString("TelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbaruar.
        /// </summary>
        internal static string TerminatedLabel {
            get {
                return ResourceManager.GetString("TerminatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kushtet e përdorimit.
        /// </summary>
        internal static string TermsOfUseLabel {
            get {
                return ResourceManager.GetString("TermsOfUseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisht.
        /// </summary>
        internal static string ThereAreNrLabel {
            get {
                return ResourceManager.GetString("ThereAreNrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deri më.
        /// </summary>
        internal static string TillLabel {
            get {
                return ResourceManager.GetString("TillLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totali.
        /// </summary>
        internal static string TotalLabel {
            get {
                return ResourceManager.GetString("TotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipi.
        /// </summary>
        internal static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlefshmëria.
        /// </summary>
        internal static string ValidityLabel {
            get {
                return ResourceManager.GetString("ValidityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlera.
        /// </summary>
        internal static string ValueLabel {
            get {
                return ResourceManager.GetString("ValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fzone është një portal &quot;privat&quot; që ofron shitje online
        ///të markave të modës më të njohura, me ulje deri në 70%. Bëhu pjesë e club-it tani!.
        /// </summary>
        internal static string WhatIsFzoneLabel {
            get {
                return ResourceManager.GetString("WhatIsFzoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrier.
        /// </summary>
        internal static string WithCarrierLabel {
            get {
                return ResourceManager.GetString("WithCarrierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femra.
        /// </summary>
        internal static string WomanMenuLabel {
            get {
                return ResourceManager.GetString("WomanMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punësime.
        /// </summary>
        internal static string WorkWithUsLabel {
            get {
                return ResourceManager.GetString("WorkWithUsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po.
        /// </summary>
        internal static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIVERSI YT.
        /// </summary>
        internal static string YourUniverseLabel {
            get {
                return ResourceManager.GetString("YourUniverseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP (kod postar).
        /// </summary>
        internal static string ZIPCodeLabel {
            get {
                return ResourceManager.GetString("ZIPCodeLabel", resourceCulture);
            }
        }
    }
}
